"""
Every category must exist everywhere it is used.

A category lives in four places: the training data, the runbook
(backend/src/knowledge/runbook.js), the frontend title map
(frontend/src/components/ClassifierPrediction.jsx) and the trained model. Add
one to the data but forget the runbook, and the model can predict a category
the LLM has no steps for. These files are in three languages, so no compiler
can catch that - this test does.
"""

import json
import re
import unittest
from pathlib import Path

from predict import UNKNOWN_LABEL

ML = Path(__file__).resolve().parent.parent
REPO = ML.parent
DATA_FILES = [ML / "data" / "incidents.jsonl", ML / "data" / "loghub_incidents.jsonl"]
RUNBOOK = REPO / "backend" / "src" / "knowledge" / "runbook.js"
FRONTEND_TITLES = REPO / "frontend" / "src" / "components" / "ClassifierPrediction.jsx"


def dataset_labels():
    labels = set()
    for path in DATA_FILES:
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.strip():
                labels.add(json.loads(line)["label"])
    return labels


class CategoriesTest(unittest.TestCase):
    def setUp(self):
        self.labels = dataset_labels()

    def test_unknown_is_never_a_hand_labelled_category(self):
        # "unknown" is generated by augment.py; a row labelled with it by hand
        # would blur what the class means.
        self.assertNotIn(UNKNOWN_LABEL, self.labels)

    def test_every_label_has_a_runbook_entry(self):
        runbook_ids = set(re.findall(r"id:\s*'([^']+)'", RUNBOOK.read_text(encoding="utf-8")))
        self.assertEqual(self.labels - runbook_ids, set(), "labels with no runbook entry")
        self.assertEqual(runbook_ids - self.labels, set(), "runbook entries with no training data")

    def test_every_label_has_a_frontend_title(self):
        source = FRONTEND_TITLES.read_text(encoding="utf-8")
        titles = set(re.findall(r"'([a-z0-9-]+)':\s*'", source))
        self.assertEqual(self.labels - titles, set(), "labels the UI would show as a raw id")

    def test_categories_are_roughly_balanced(self):
        # A category with far fewer examples gets predicted far less often.
        counts = {}
        for path in DATA_FILES:
            for line in path.read_text(encoding="utf-8").splitlines():
                if line.strip():
                    label = json.loads(line)["label"]
                    counts[label] = counts.get(label, 0) + 1
        smallest, largest = min(counts.values()), max(counts.values())
        self.assertLessEqual(largest / smallest, 2, counts)


if __name__ == "__main__":
    unittest.main()
